Traceback (most recent call last):
  File "/home/runner/work/AdventOfCode2022/AdventOfCode2022/s1effen/06/./challenge", line 4, in <module>
    with open(sys.argv[1], "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/AdventOfCode2022/AdventOfCode2022/main/.github/scripts/../../.github/challenges/06.txt'
